# Generated by Django 4.0.4 on 2023-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_added',
        ),
        migrations.AddField(
            model_name='address',
            name='card_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='credit_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='exp_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='exp_year',
            field=models.IntegerField(null=True),
        ),
    ]
