# Generated by Django 4.0.4 on 2023-05-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_date_added_address_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='exp_month',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
