# Generated by Django 4.0.4 on 2023-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_address_exp_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='exp_month',
            field=models.IntegerField(null=True),
        ),
    ]
